name: release
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published, created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: rohilsurana/helm-gh-pages@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: stable
