name: release
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published, created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@d7b00680cb32bea80178ea7da18219b0d7ac02b7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: stable
